//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entidade", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService")]
    public partial class Entidade : object
    {
        
        private int AnoField;
        
        private string CodEntidadeField;
        
        private string CodEntidadePaiField;
        
        private int CodTipoEntidadeField;
        
        private int CodTipoEntidadePaiField;
        
        private string DescricaoStatusPoloField;
        
        private string DescricaoTipoEntidadeField;
        
        private string MensagemField;
        
        private string MunicipioField;
        
        private string NomeEntidadeField;
        
        private string NomeEntidadePaiField;
        
        private string NomePoloField;
        
        private string NomeTipoEntidadePaiField;
        
        private string NumeroAtaField;
        
        private bool StatusField;
        
        private string TelefoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ano
        {
            get
            {
                return this.AnoField;
            }
            set
            {
                this.AnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEntidade
        {
            get
            {
                return this.CodEntidadeField;
            }
            set
            {
                this.CodEntidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEntidadePai
        {
            get
            {
                return this.CodEntidadePaiField;
            }
            set
            {
                this.CodEntidadePaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodTipoEntidade
        {
            get
            {
                return this.CodTipoEntidadeField;
            }
            set
            {
                this.CodTipoEntidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodTipoEntidadePai
        {
            get
            {
                return this.CodTipoEntidadePaiField;
            }
            set
            {
                this.CodTipoEntidadePaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatusPolo
        {
            get
            {
                return this.DescricaoStatusPoloField;
            }
            set
            {
                this.DescricaoStatusPoloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoTipoEntidade
        {
            get
            {
                return this.DescricaoTipoEntidadeField;
            }
            set
            {
                this.DescricaoTipoEntidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio
        {
            get
            {
                return this.MunicipioField;
            }
            set
            {
                this.MunicipioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeEntidade
        {
            get
            {
                return this.NomeEntidadeField;
            }
            set
            {
                this.NomeEntidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeEntidadePai
        {
            get
            {
                return this.NomeEntidadePaiField;
            }
            set
            {
                this.NomeEntidadePaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomePolo
        {
            get
            {
                return this.NomePoloField;
            }
            set
            {
                this.NomePoloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTipoEntidadePai
        {
            get
            {
                return this.NomeTipoEntidadePaiField;
            }
            set
            {
                this.NomeTipoEntidadePaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAta
        {
            get
            {
                return this.NumeroAtaField;
            }
            set
            {
                this.NumeroAtaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                this.TelefoneField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntidadesService.IEntidade")]
    public interface IEntidade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidade/RetornaEntidades", ReplyAction="http://tempuri.org/IEntidade/RetornaEntidadesResponse")]
        System.Threading.Tasks.Task<EntidadesService.Entidade[]> RetornaEntidadesAsync(string Chave1, string Chave2, string CodEntidade, System.Nullable<int> NumeroPolo, int Ano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidade/RetornaPolos", ReplyAction="http://tempuri.org/IEntidade/RetornaPolosResponse")]
        System.Threading.Tasks.Task<EntidadesService.Entidade[]> RetornaPolosAsync(string Chave1, string Chave2, string NumeroAta, System.Nullable<int> NumeroPolo, int Ano);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IEntidadeChannel : EntidadesService.IEntidade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EntidadeClient : System.ServiceModel.ClientBase<EntidadesService.IEntidade>, EntidadesService.IEntidade
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EntidadeClient() : 
                base(EntidadeClient.GetDefaultBinding(), EntidadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEntidade.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadeClient(EndpointConfiguration endpointConfiguration) : 
                base(EntidadeClient.GetBindingForEndpoint(endpointConfiguration), EntidadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EntidadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EntidadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EntidadesService.Entidade[]> RetornaEntidadesAsync(string Chave1, string Chave2, string CodEntidade, System.Nullable<int> NumeroPolo, int Ano)
        {
            return base.Channel.RetornaEntidadesAsync(Chave1, Chave2, CodEntidade, NumeroPolo, Ano);
        }
        
        public System.Threading.Tasks.Task<EntidadesService.Entidade[]> RetornaPolosAsync(string Chave1, string Chave2, string NumeroAta, System.Nullable<int> NumeroPolo, int Ano)
        {
            return base.Channel.RetornaPolosAsync(Chave1, Chave2, NumeroAta, NumeroPolo, Ano);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEntidade))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEntidade))
            {
                return new System.ServiceModel.EndpointAddress("http://homologwsrededesup.fde.sp.gov.br/WebserviceRedeSup/WcfRedeSupService.Entid" +
                        "ades.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EntidadeClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEntidade);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EntidadeClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEntidade);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEntidade,
        }
    }
}
