//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutosService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusProdutoItem", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public enum StatusProdutoItem : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendenteDeAprovacao = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Negado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ativo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inativo = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoItem", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public partial class ProdutoItem : object
    {
        
        private System.DateTime DataInclusaoBaseField;
        
        private string DescricaoProdutoField;
        
        private string DescricaoStatusProdutoField;
        
        private string DescricaoStatusProdutoItemField;
        
        private string JustificativaSituacaoField;
        
        private string MarcaProdutoField;
        
        private string MensagemField;
        
        private string NomeAmigavelProdutoField;
        
        private string NumeroAtaField;
        
        private string NumeroFDEItemField;
        
        private string NumeroItemFornecedorField;
        
        private System.Nullable<int> NumeroProdutoField;
        
        private bool StatusField;
        
        private ProdutosService.StatusProduto StatusProdutoField;
        
        private ProdutosService.StatusProdutoItem StatusProdutoItemField;
        
        private decimal Vl_PrecoUnitarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataInclusaoBase
        {
            get
            {
                return this.DataInclusaoBaseField;
            }
            set
            {
                this.DataInclusaoBaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoProduto
        {
            get
            {
                return this.DescricaoProdutoField;
            }
            set
            {
                this.DescricaoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatusProduto
        {
            get
            {
                return this.DescricaoStatusProdutoField;
            }
            set
            {
                this.DescricaoStatusProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatusProdutoItem
        {
            get
            {
                return this.DescricaoStatusProdutoItemField;
            }
            set
            {
                this.DescricaoStatusProdutoItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JustificativaSituacao
        {
            get
            {
                return this.JustificativaSituacaoField;
            }
            set
            {
                this.JustificativaSituacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarcaProduto
        {
            get
            {
                return this.MarcaProdutoField;
            }
            set
            {
                this.MarcaProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeAmigavelProduto
        {
            get
            {
                return this.NomeAmigavelProdutoField;
            }
            set
            {
                this.NomeAmigavelProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAta
        {
            get
            {
                return this.NumeroAtaField;
            }
            set
            {
                this.NumeroAtaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFDEItem
        {
            get
            {
                return this.NumeroFDEItemField;
            }
            set
            {
                this.NumeroFDEItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroItemFornecedor
        {
            get
            {
                return this.NumeroItemFornecedorField;
            }
            set
            {
                this.NumeroItemFornecedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroProduto
        {
            get
            {
                return this.NumeroProdutoField;
            }
            set
            {
                this.NumeroProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProdutosService.StatusProduto StatusProduto
        {
            get
            {
                return this.StatusProdutoField;
            }
            set
            {
                this.StatusProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProdutosService.StatusProdutoItem StatusProdutoItem
        {
            get
            {
                return this.StatusProdutoItemField;
            }
            set
            {
                this.StatusProdutoItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vl_PrecoUnitario
        {
            get
            {
                return this.Vl_PrecoUnitarioField;
            }
            set
            {
                this.Vl_PrecoUnitarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusProduto", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public enum StatusProduto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inativo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ativo = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmaProduto", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public partial class ConfirmaProduto : object
    {
        
        private string SituacaoRetornoField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SituacaoRetorno
        {
            get
            {
                return this.SituacaoRetornoField;
            }
            set
            {
                this.SituacaoRetornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosImagemProduto", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public partial class DadosImagemProduto : object
    {
        
        private string DescricaoImagemField;
        
        private int Fl_PrincipalField;
        
        private string NumeroAtaField;
        
        private string NumeroFDEItemField;
        
        private string NumeroItemFornecedorField;
        
        private int NumeroOrdemField;
        
        private System.Nullable<int> NumeroProdutoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoImagem
        {
            get
            {
                return this.DescricaoImagemField;
            }
            set
            {
                this.DescricaoImagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fl_Principal
        {
            get
            {
                return this.Fl_PrincipalField;
            }
            set
            {
                this.Fl_PrincipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAta
        {
            get
            {
                return this.NumeroAtaField;
            }
            set
            {
                this.NumeroAtaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFDEItem
        {
            get
            {
                return this.NumeroFDEItemField;
            }
            set
            {
                this.NumeroFDEItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroItemFornecedor
        {
            get
            {
                return this.NumeroItemFornecedorField;
            }
            set
            {
                this.NumeroItemFornecedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroOrdem
        {
            get
            {
                return this.NumeroOrdemField;
            }
            set
            {
                this.NumeroOrdemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroProduto
        {
            get
            {
                return this.NumeroProdutoField;
            }
            set
            {
                this.NumeroProdutoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutosService.IProdutos")]
    public interface IProdutos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutos/RetornaProdutosPropostos", ReplyAction="http://tempuri.org/IProdutos/RetornaProdutosPropostosResponse")]
        System.Threading.Tasks.Task<ProdutosService.ProdutoItem[]> RetornaProdutosPropostosAsync(string Chave1, string Chave2, string NumeroAta, System.Nullable<int> NumeroProduto, ProdutosService.StatusProdutoItem SituacaoProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutos/RetornaProdutosLoja", ReplyAction="http://tempuri.org/IProdutos/RetornaProdutosLojaResponse")]
        System.Threading.Tasks.Task<ProdutosService.ProdutoItem[]> RetornaProdutosLojaAsync(string Chave1, string Chave2, string NumeroAta, System.Nullable<int> NumeroProduto, ProdutosService.StatusProduto StatusProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutos/AtualizaProduto", ReplyAction="http://tempuri.org/IProdutos/AtualizaProdutoResponse")]
        System.Threading.Tasks.Task<ProdutosService.ConfirmaProduto> AtualizaProdutoAsync(string Chave1, string Chave2, ProdutosService.ProdutoItem NovoProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutos/UploadImagemProduto", ReplyAction="http://tempuri.org/IProdutos/UploadImagemProdutoResponse")]
        System.Threading.Tasks.Task<ProdutosService.Confirmation> UploadImagemProdutoAsync(ProdutosService.RemoteFileInfoProduto request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfoProduto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfoProduto
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Chave1;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Chave2;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ProdutosService.DadosImagemProduto DadosProdutoImagem;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Stream;
        
        public RemoteFileInfoProduto()
        {
        }
        
        public RemoteFileInfoProduto(string Chave1, string Chave2, ProdutosService.DadosImagemProduto DadosProdutoImagem, string FileName, System.IO.Stream Stream)
        {
            this.Chave1 = Chave1;
            this.Chave2 = Chave2;
            this.DadosProdutoImagem = DadosProdutoImagem;
            this.FileName = FileName;
            this.Stream = Stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Confirmation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Confirmation
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SituacaoRetorno;
        
        public Confirmation()
        {
        }
        
        public Confirmation(bool Status, string SituacaoRetorno)
        {
            this.Status = Status;
            this.SituacaoRetorno = SituacaoRetorno;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IProdutosChannel : ProdutosService.IProdutos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ProdutosClient : System.ServiceModel.ClientBase<ProdutosService.IProdutos>, ProdutosService.IProdutos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProdutosClient() : 
                base(ProdutosClient.GetDefaultBinding(), ProdutosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProdutos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutosClient(EndpointConfiguration endpointConfiguration) : 
                base(ProdutosClient.GetBindingForEndpoint(endpointConfiguration), ProdutosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProdutosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProdutosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProdutosService.ProdutoItem[]> RetornaProdutosPropostosAsync(string Chave1, string Chave2, string NumeroAta, System.Nullable<int> NumeroProduto, ProdutosService.StatusProdutoItem SituacaoProduto)
        {
            return base.Channel.RetornaProdutosPropostosAsync(Chave1, Chave2, NumeroAta, NumeroProduto, SituacaoProduto);
        }
        
        public System.Threading.Tasks.Task<ProdutosService.ProdutoItem[]> RetornaProdutosLojaAsync(string Chave1, string Chave2, string NumeroAta, System.Nullable<int> NumeroProduto, ProdutosService.StatusProduto StatusProduto)
        {
            return base.Channel.RetornaProdutosLojaAsync(Chave1, Chave2, NumeroAta, NumeroProduto, StatusProduto);
        }
        
        public System.Threading.Tasks.Task<ProdutosService.ConfirmaProduto> AtualizaProdutoAsync(string Chave1, string Chave2, ProdutosService.ProdutoItem NovoProduto)
        {
            return base.Channel.AtualizaProdutoAsync(Chave1, Chave2, NovoProduto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProdutosService.Confirmation> ProdutosService.IProdutos.UploadImagemProdutoAsync(ProdutosService.RemoteFileInfoProduto request)
        {
            return base.Channel.UploadImagemProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProdutosService.Confirmation> UploadImagemProdutoAsync(string Chave1, string Chave2, ProdutosService.DadosImagemProduto DadosProdutoImagem, string FileName, System.IO.Stream Stream)
        {
            ProdutosService.RemoteFileInfoProduto inValue = new ProdutosService.RemoteFileInfoProduto();
            inValue.Chave1 = Chave1;
            inValue.Chave2 = Chave2;
            inValue.DadosProdutoImagem = DadosProdutoImagem;
            inValue.FileName = FileName;
            inValue.Stream = Stream;
            return ((ProdutosService.IProdutos)(this)).UploadImagemProdutoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProdutos))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProdutos))
            {
                return new System.ServiceModel.EndpointAddress("http://homologwsrededesup.fde.sp.gov.br/WebserviceRedeSup/WcfRedeSupService.Produ" +
                        "tos.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProdutosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProdutos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProdutosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProdutos);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProdutos,
        }
    }
}
