//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdensFornecimentoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdemFornecimento", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public partial class OrdemFornecimento : object
    {
        
        private OrdensFornecimentoService.Confirmation ConfirmationField;
        
        private System.DateTime DataAssinaturaOSOFField;
        
        private string NumeroOSOFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrdensFornecimentoService.Confirmation Confirmation
        {
            get
            {
                return this.ConfirmationField;
            }
            set
            {
                this.ConfirmationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAssinaturaOSOF
        {
            get
            {
                return this.DataAssinaturaOSOFField;
            }
            set
            {
                this.DataAssinaturaOSOFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroOSOF
        {
            get
            {
                return this.NumeroOSOFField;
            }
            set
            {
                this.NumeroOSOFField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Confirmation", Namespace="http://schemas.datacontract.org/2004/07/WcfRedeSupService.Interfaces")]
    public partial class Confirmation : object
    {
        
        private string SituacaoRetornoField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SituacaoRetorno
        {
            get
            {
                return this.SituacaoRetornoField;
            }
            set
            {
                this.SituacaoRetornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdensFornecimentoService.IOrdemFornecimento")]
    public interface IOrdemFornecimento
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemFornecimento/RetornaOrdemFornecimentos", ReplyAction="http://tempuri.org/IOrdemFornecimento/RetornaOrdemFornecimentosResponse")]
        System.Threading.Tasks.Task<OrdensFornecimentoService.OrdemFornecimento[]> RetornaOrdemFornecimentosAsync(string Chave1, string Chave2, string NumeroOSOF, System.Nullable<System.DateTime> DtInicial, System.Nullable<System.DateTime> DtFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IOrdemFornecimentoChannel : OrdensFornecimentoService.IOrdemFornecimento, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OrdemFornecimentoClient : System.ServiceModel.ClientBase<OrdensFornecimentoService.IOrdemFornecimento>, OrdensFornecimentoService.IOrdemFornecimento
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrdemFornecimentoClient() : 
                base(OrdemFornecimentoClient.GetDefaultBinding(), OrdemFornecimentoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOrdemFornecimento.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdemFornecimentoClient(EndpointConfiguration endpointConfiguration) : 
                base(OrdemFornecimentoClient.GetBindingForEndpoint(endpointConfiguration), OrdemFornecimentoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdemFornecimentoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrdemFornecimentoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdemFornecimentoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrdemFornecimentoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdemFornecimentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OrdensFornecimentoService.OrdemFornecimento[]> RetornaOrdemFornecimentosAsync(string Chave1, string Chave2, string NumeroOSOF, System.Nullable<System.DateTime> DtInicial, System.Nullable<System.DateTime> DtFinal)
        {
            return base.Channel.RetornaOrdemFornecimentosAsync(Chave1, Chave2, NumeroOSOF, DtInicial, DtFinal);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrdemFornecimento))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrdemFornecimento))
            {
                return new System.ServiceModel.EndpointAddress("http://homologwsrededesup.fde.sp.gov.br/WebserviceRedeSup/WcfRedeSupService.Ordem" +
                        "Fornecimento.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrdemFornecimentoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOrdemFornecimento);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrdemFornecimentoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOrdemFornecimento);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOrdemFornecimento,
        }
    }
}
